# Python basics

In [ ]:
2+5

7

In [ ]:
print('Hello')

Hello


## Variables

In [ ]:
x=1
print(x)
print(x)

1
1


In [ ]:
x=x+1
print(x)

5


In [ ]:
print('aaaa')
print(4)
print(x+4)

aaaa
4
8


In [ ]:
y='Amir'
print(y)

Amir


# Logic

In [ ]:
x



2.5

In [ ]:

if x > 3:
  x=x-1
print(x)


3


In [ ]:
if x > 3:
  x=x-1
  print(x)


In [ ]:
if x > 3:
  x=x-1
else:
    x=x+0.5
print(x)

3.0


In [ ]:
x

3

## NumPy

In [ ]:
import numpy as np

In [ ]:
lst=[1,2,3]
lst

[1, 2, 3]

In [ ]:
arr1=np.array(lst)
arr1

array([1, 2, 3])

In [ ]:
arr2=np.array([2,3,4])
arr2

array([2, 3, 4])

In [ ]:
arr2.shape


(3,)

In [ ]:
arr1.shape

(3,)

In [ ]:
np.arange(1,20,5)

array([ 1,  6, 11, 16])

In [ ]:
np.linspace(1,16,4)

array([ 1.,  6., 11., 16.])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.random.rand(10)

array([0.84144591, 0.73930048, 0.5981817 , 0.93306659, 0.03568695,
       0.38588617, 0.72603548, 0.50779011, 0.00857739, 0.50204229])

In [ ]:
np.random.randint(1,10,5)

array([4, 5, 8, 2, 3])